name: e2e tests

on:
  schedule:
    - cron: "0 9 * * 1" # every monday at 9:00
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Run gwatlin e2e tests
        run: ./run-e2e-suite.sh